### ISSUE TITLE
请问有没有考虑过添加右边栏内容同时滚动的功能？

### ISSUE THREAD

**Issue by FunnyWii** [Anyexyz/theme-vcard4#1]
目录可以滚动，效果非常nice
要不要考虑加入整个右边栏同时滚动的功能？
这样就可以避免目录遮挡一部分边栏了，有些突兀
![image](https://github.com/user-attachments/assets/b66e3130-d6fd-48ba-90f3-799cc6e1a7ba)

**Comment by Anyexyz** [comment]
该主题是 [halo-dev/theme-earth](https://github.com/halo-dev/theme-earth)，非本主题
